package com.example.driedpork.model.coingecko

data class Market(
    val id: String,
    val symbol: String,
    val name: String,
    val image: String? = null,
    val current_price: Double = 0.0,
    val market_cap: Double = 0.0,
    val market_cap_rank: Long = 0,
    val total_volume: Double = 0.0,
    val high_24h: Double = 0.0,
    val low_24h: Double = 0.0,
    val price_change_24h: Double = 0.0,
    val price_change_percentage_24h: Double = 0.0,
    val market_cap_change_24h: Double = 0.0,
    val market_cap_change_percentage_24h: Double = 0.0,
    val circulating_supply: Double = 0.0,
    val total_supply: Double? = null,
    val ath: Double = 0.0,
    val atl: Double = 0.0,
    val atl_change_percentage: Double = 0.0,
    val ath_change_percentage: Double = 0.0,
    val atl_date: String? = null,
    val ath_date: String? = null,
    val roi: Any? = null,
    val last_updated: String? = null,
    val sparkline_in_7d: Any? = null,
    val price_change_percentage_1h_in_currency: Double = 0.0,
    val fully_diluted_valuation: Double?,
    val max_supply: Double? = 0.0,
)
